from .header.page_object import Header
from .login_page.page_object import LoginPage
from .studios_page.page_object import Studios
from .add_studio_page.page_object import AddStudio
from .add_title_page.page_object import AddTitle
from .sidebar_page.page_object import Sidebar
from .catalogs_page.page_object import Catalogs
from .titles_page.page_object import Titles
from .storefronts_page.page_object import Storefronts
from .catalog_overview_page.page_object import CatalogOverview
from .notification.page_object import Notification
from .header.page_object import Header
from .catalog_tabs_page.page_object import CatalogTabs
from .products_page.page_object import Products
from .entitlements_page.page_object import Entitlements
from .currencies_page.page_object import Currencies
from .environments_page.page_object import Environments
from .add_catalog_page.page_object import AddCatalog
from .add_storefront_page.page_object import AddStorefront
from .add_entitlement_page.page_object import AddEntitlement
from .add_currency_page.page_object import AddCurrency
from .add_product_page.page_object import AddProduct
from .edit_entitlement_page.page_object import EditEntitlement
from .actions_menu.page_object import ActionsMenu
from .add_entity_to_entity_page.page_object import AddEntityToEntity
from .edit_storefront_page.page_object import EditStorefront
from .edit_product_page.page_object import EditProduct
from .players_page.page_object import Players
from .add_player_page.page_object import AddPlayer
from .add_bulk_players_page.page_object import AddBulkPlayers
from .edit_player_page.page_object import EditPlayer
from .add_game_registration_page.page_object import AddGameRegistration
from .edit_currency_page.page_object import EditCurrency
from .add_prices_to_product_page.page_object import AddPricesToProduct
